#!/usr/bin/env python3
"""
FreshSites Delivery Agent
Handles post-purchase: zips the demo page, generates transfer instructions,
and prepares hosting handoff for the buyer.

Usage:
    PYTHONPATH="" ./.venv/bin/python3.11 agents/deliver.py <lead_id>
"""

import json
import sqlite3
import shutil
import zipfile
from datetime import datetime
from pathlib import Path

DB_PATH = Path(__file__).parent.parent / "leads" / "freshsites.db"
DEMOS_DIR = Path(__file__).parent.parent / "demos"
OUTPUT_DIR = Path(__file__).parent.parent / "deliveries"


def get_lead(lead_id: int) -> dict:
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    c = conn.cursor()
    c.execute("SELECT * FROM leads WHERE id = ?", (lead_id,))
    row = c.fetchone()
    conn.close()
    return dict(row) if row else None


def slugify(name: str) -> str:
    return name.lower().replace("'", "").replace(" ", "-").replace("&", "and")


def create_delivery_package(lead: dict) -> Path:
    """
    Create a zip file containing:
    1. The demo HTML page
    2. Transfer instructions (README)
    3. Hosting guide
    4. Customization guide
    """
    name = lead["name"]
    slug = slugify(name)
    demo_file = DEMOS_DIR / f"{slug}.html"
    if not demo_file.exists():
        # Try alternative naming
        alt_slugs = [
            slug.replace("-", "_"),
            slug.replace("&", "and"),
            slug.replace("'", ""),
        ]
        for alt in alt_slugs:
            candidate = DEMOS_DIR / f"{alt}.html"
            if candidate.exists():
                demo_file = candidate
                break

    if not demo_file.exists():
        print(f"❌ Demo file not found: {demo_file}")
        return None

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    out_dir = OUTPUT_DIR / f"{slug}_{timestamp}"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Copy the HTML
    shutil.copy(demo_file, out_dir / "index.html")

    # Create README
    readme = f"""# {name} — Website Delivery Package

Generated by FreshSites on {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}

## 📦 What's Included

- `index.html` — Your complete landing page (this is your website)

## 🚀 How to Make It Live

### Option A: Free Hosting (GitHub Pages) — Recommended
1. Go to https://github.com/new
2. Create a new public repository named `{slug}-website`
3. Upload `index.html` to the repository root
4. Go to Settings → Pages → Select "Deploy from branch" → Choose "main" → Select "/ (root)"
5. Your site will be live at `https://yourusername.github.io/{slug}-website/`

### Option B: Netlify Drop (Free)
1. Go to https://app.netlify.com/drop
2. Drag and drop `index.html` into the upload area
3. Netlify gives you a free `.netlify.app` URL instantly

### Option C: Your Existing Web Host
1. Rename `index.html` to whatever your host requires (usually keep it as `index.html`)
2. Upload via FTP/cPanel/File Manager to your web root
3. If you have an existing site, back up first, then overwrite

## 🎨 Customization Guide

### Change text:
Open `index.html` in any text editor (Notepad, VS Code, TextEdit).
Search for the text you want to change and edit it.

### Add your photos:
Replace the SVG illustrations with `<img src="your-photo.jpg">` tags.
Upload your photos alongside `index.html` and reference them.

### Change colors:
Look for `:root` near the top of the file. Edit the color codes:
- `--brand-blue` — your main brand color
- `--brand-gold` — accent color (buttons, highlights)
- `--brand-dark` — dark sections

### Add Google Analytics:
Paste your GA4 tracking code inside `<head>` before `</head>`.

## 📞 Need Help?

Email freshsites@sites.propagate.media for:
- Custom changes (£50-150 depending on scope)
- Additional pages
- Logo integration
- Domain connection

---
© FreshSites by Propagate Media
"""
    (out_dir / "README.md").write_text(readme, encoding="utf-8")

    # Create zip
    zip_path = OUTPUT_DIR / f"{slug}_freshsites_{timestamp}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for f in out_dir.iterdir():
            zf.write(f, f.name)

    # Clean up temp dir
    shutil.rmtree(out_dir)

    print(f"✅ Package created: {zip_path}")
    print(f"   Size: {zip_path.stat().st_size / 1024:.1f} KB")
    return zip_path


def generate_post_purchase_email(lead: dict, zip_path: Path) -> str:
    """Generate the delivery email sent after purchase."""
    return f"""From: FreshSites <freshsites@sites.propagate.media>
To: {lead["name"]} <{lead["email"] or "customer@example.com"}>
Subject: Your {lead["name"]} website is ready
Content-Type: text/html; charset=utf-8

<!DOCTYPE html>
<html>
<body style="font-family:Inter,sans-serif;color:#1a1a1a;background:#fff;margin:0;padding:0;">
<div style="max-width:600px;margin:0 auto;padding:40px 24px;">
  <h2 style="color:#0A0A0A;">🎉 Your page is ready!</h2>
  <p>Thanks for purchasing the {lead["name"]} landing page.</p>
  <p><strong>Your demo page:</strong> <a href="{lead["demo_url"]}">{lead["demo_url"]}</a></p>
  <p>Download your files from the attachment and follow the README to deploy.</p>
  <p style="background:#f5f5f5;padding:16px;border-radius:6px;">
    <strong>Next step:</strong> Upload <code>index.html</code> to GitHub Pages, Netlify, or your web host.
    Full instructions in README.md.
  </p>
  <p>Need changes? Reply to this email.</p>
  <p>— FreshSites</p>
</div>
</body>
</html>
"""


def mark_delivered(lead_id: int):
    conn = sqlite3.connect(str(DB_PATH))
    c = conn.cursor()
    c.execute(
        "UPDATE leads SET status = 'converted', updated_at = ? WHERE id = ?",
        (datetime.utcnow().isoformat(), lead_id),
    )
    conn.commit()
    conn.close()


def main():
    import sys
    if len(sys.argv) < 2:
        print("Usage: deliver.py <lead_id>")
        print("\nAvailable leads with demos:")
        conn = sqlite3.connect(str(DB_PATH))
        c = conn.cursor()
        c.execute("SELECT id, name, status, demo_url FROM leads WHERE demo_url IS NOT NULL")
        for row in c.fetchall():
            print(f"  {row[0]:3d} | {row[1]:30s} | {row[2]:12s} | {row[3]}")
        conn.close()
        return

    lead_id = int(sys.argv[1])
    lead = get_lead(lead_id)
    if not lead:
        print(f"Lead {lead_id} not found")
        return

    print(f"📦 Creating delivery for: {lead['name']}")
    zip_path = create_delivery_package(lead)
    if zip_path:
        email = generate_post_purchase_email(lead, zip_path)
        email_path = zip_path.parent / f"{slugify(lead['name'])}_email.eml"
        email_path.write_text(email, encoding="utf-8")
        print(f"   Email template: {email_path}")
        print(f"\n📋 SUMMARY")
        print(f"   Lead: {lead['name']}")
        print(f"   Package: {zip_path}")
        print(f"   Demo: {lead['demo_url']}")
        print(f"\n   ✅ Ready to send. Use Himalaya or manual email client.")


if __name__ == "__main__":
    main()
