#!/usr/bin/env python3
"""Generate 10 FreshSites demos with all sections intact."""
from pathlib import Path
from string import Template

IMAGES = {
    "hero_workshop": "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=1600&h=700&fit=crop&q=80",
    "hero_garage": "https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=1600&h=700&fit=crop&q=80",
    "about_mechanic": "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&h=500&fit=crop&q=80",
    "svc_workshop": "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=500&h=280&fit=crop&q=80",
    "svc_diagnostics": "https://images.unsplash.com/photo-1578844251758-2f71da64c96f?w=500&h=280&fit=crop&q=80",
    "svc_tyres": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=500&h=280&fit=crop&q=80",
    "svc_brakes": "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=500&h=280&fit=crop&q=80",
    "svc_servicing": "https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=500&h=280&fit=crop&q=80",
    "svc_engine": "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=500&h=280&fit=crop&q=80",
}

LEADS = [
    {"name":"M.E. Poston Motors","slug":"meposton-motors","color":"#e8a010","phone":"01686 630 653","loc":"Abermule, Montgomery, SY15 6ND","hours":"Monday - Friday: 8:30AM - 5:30PM | Saturday: By Appointment Only","badge":"Established 1938","hero":"Engineers to the Motor Trade Since 1938","desc":"Full workshop facilities for car servicing, repairs, diagnostics, clutches, brakes and engine tuning","svcs":[("Autologic Diagnostics","We find the fault fast and fix it right first time."),("Brake Disc + Pad Repairs","Professional brake disc and pad replacements for safe stopping."),("Breakdown Recovery","Breakdown recovery service to get you back on the road quickly."),("Cambelt Replacement","Protect your engine from costly damage with essential maintenance."),("Car Batteries","Quality batteries fitted by experienced engineers."),("Car Repairs","No job too large or too small. All makes and models welcome."),("Car Servicing","Keep your vehicle running smoothly with comprehensive servicing."),("Clutch + DMF Replacements","Expert clutch replacements with dual mass flywheel repairs."),("Engine Tuning + Remapping","Improve performance and fuel efficiency with professional tuning."),],"about":"M.E. Poston Motors has been operating as a long established engineering workshop in the heart of Mid Wales since 1938. We strive for excellence and understand the importance of good customer service.","map":"https://www.google.com/maps?q=Abermule+SY156ND&output=embed"},
    {"name":"Crossing Garage","slug":"crossing-garage","color":"#0077be","phone":"01597 829243","loc":"Llandrindod Wells, Powys, LD1 6AA","hours":"Monday - Friday: 8:30 - 17:30 | Saturday: CLOSED | Sunday: CLOSED","badge":"Independent Garage","hero":"Car & Light Commercial Servicing in Llandrindod Wells","desc":"Servicing, MOT, tyres, exhausts, repairs, air-con, timing belts and more for cars and light commercial vehicles throughout Mid Wales.","svcs":[("Car & Light Commercial Servicing","Full servicing with high quality oils from Comma and Forte."),("MOT Testing"," cars, vans and light commercials. Book up to a month before expiry."),("Tyres","Supply, fitting and puncture repairs. Quality tyres at competitive prices."),("Exhausts","Repairs and replacements. Quality parts fitted by experienced mechanics."),("Repairs & Parts","Brakes to suspension, we keep your vehicle roadworthy and safe."),("Air-Con Servicing","Servicing and re-gas so your system works efficiently."),("Timing Belts","Essential maintenance to protect your engine from costly damage."),("Headlamp Refurbishment","Restore clarity and improve visibility cost-effectively."),("Clutches","Repairs and replacements for cars and light commercial vehicles."),],"about":"Crossing Garage is an independent garage in Llandrindod Wells offering a full range of services for car and light commercial vehicle owners throughout Mid Wales. We pride ourselves on honest, reliable service at competitive prices.","map":"https://www.google.com/maps?q=Llandrindod+Wells+LD16AA&output=embed"},
    {"name":"Graig Goch Garage","slug":"graig-goch","color":"#c41e3a","phone":"01982 554695","loc":"Cwmbach, Builth Wells, LD2 3RU","hours":"Monday - Friday: 8:00 - 17:30 | Saturday: 8:00 - 12:00","badge":"DVSA Approved Station","hero":"MOT, Servicing & Repairs in Builth Wells","desc":"Full workshop facilities. Competitive prices. Local collection and delivery. No job too large or too small.","svcs":[("MOT Testing Station","Classes 4 and 7 including cars, vans and goods vehicles up to 3,500kg."),("Pre-MOT Service","Help your vehicle pass first time with our pre-MOT checks."),("Servicing","Full workshop facilities. All makes and models at competitive prices."),("General Repairs","No job too large or too small. Reliable workmanship guaranteed."),("Tyres","Supply and fitting at competitive prices."),("Collection & Delivery","Local collection and delivery service for your convenience."),],"about":"Graig Goch Garage in Builth Wells is a DVSA approved MOT testing station. We provide full workshop facilities with competitive prices and a collection and delivery service. No job is too large or too small.","map":"https://www.google.com/maps?q=Builth+Wells+LD23RU&output=embed"},
    {"name":"Bradleys Garage","slug":"bradleys-garage","color":"#c41e3a","phone":"01686 430 002","loc":"Llanidloes, Powys, SY18 6RB","hours":"Monday - Friday: 8:30 - 17:30 | Saturday: 8:30 - 12:00","badge":"Family Run Since 1920","hero":"Full vehicle servicing, MOT testing and repairs in Mid Wales","desc":"All makes & models. Servicing, MOT, diagnostics, tyres, A/C and specialist commercial repairs.","svcs":[("Servicing & MOTs","Comprehensive servicing and MOT for all makes and models."),("Advanced Diagnostics","The latest diagnostic tools to find and fix issues fast."),("Tyres & Fitting","Tyre supply, fitting and maintenance to keep you safe."),("Air Conditioning","Full air conditioning servicing and re-gas."),("Repairs & Parts","Routine maintenance to complex repairs. All work guaranteed."),("HGV & Commercial","Commercial vehicle servicing and specialist experience since 1920."),],"about":"Family run Bradleys have been in the motor industry for almost a century. Previously Rover, Peugeot and Renault dealers, we pride ourselves on the highest level of customer care.","map":"https://www.google.com/maps?q=Llanidloes+SY186RB&output=embed"},
    {"name":"D A Autos","slug":"d-a-autos","color":"#2563eb","phone":"01938 552 245","loc":"Welshpool, Powys, SY21 7DG","hours":"Monday - Friday: 8:00 - 17:30 | Saturday: 8:00 - 12:00","badge":"Independent Family Business","hero":"Tyres, servicing, MOT prep and repairs in Welshpool","desc":"Your trusted local garage. 15+ years family-run. Tyres, servicing, MOT prep, repairs and we buy any car.","svcs":[("Tyre Supply & Fitting","Quality tyres for all makes, fitted with expert care and competitive pricing."),("Car Servicing","Comprehensive servicing from oil and filter changes to full inspections."),("MOT Preparation","Expert checks and repairs so you pass with confidence."),("Repairs & Welding","All types of repairs and welding work by experienced mechanics."),("We Buy Any Car","MOT-failed, damaged or repairable vehicles bought for cash with fast collection."),("Vehicle Collection","Fast and convenient vehicle collection throughout Powys."),],"about":"D A Autos is more than just a tyre specialist - we are your trusted local garage. Over 15 years as a family-run business delivering reliable, affordable garage services with a personal touch.","map":"https://www.google.com/maps?q=Welshpool+SY217DG&output=embed"},
    {"name":"DC Autos Newtown","slug":"dc-autos-newtown","color":"#e87900","phone":"01686 629 200","loc":"Newtown, Powys, SY16 4JJ","hours":"Monday - Friday: 8:00 - 17:00 | Saturday - Sunday: Closed","badge":"30+ Years Experience","hero":"MOTs, servicing, diagnostics and repairs for cars and vans","desc":"Your trusted, family-run garage with real-time MOT booking, diagnostics, tyres and DPF services.","svcs":[("MOT Testing","Real-time booking, reminders and re-tests available."),("Servicing & Repairs","Expert servicing using the latest diagnostic equipment."),("Diagnostics","Engine management and fault finding for all makes and models."),("Tyre Services","Supply, fitting and balancing for cars, vans and 4x4s."),("Air Conditioning","Air conditioning re-gas and repair to keep you cool."),("DPF & Flywheel","DPF cleaning, turbo repairs and dual mass flywheel replacements."),],"about":"DC Autos is a family-run garage with over 30 years of dealership-trained experience. Quality workmanship, fair pricing and honest advice you can trust.","map":"https://www.google.com/maps?q=Newtown+SY164JJ&output=embed"},
    {"name":"K's Garage","slug":"ks-garage","color":"#1d4ed8","phone":"01686 625 872","loc":"Newtown, Powys, SY16 4BQ","hours":"Monday - Friday: 8:30 - 17:00 | Saturday - Sunday: Closed","badge":"Local & Reliable","hero":"MOTs, servicing, clutches and tyres throughout Mid Wales","desc":"Wide range of motor repair services. MOTs, servicing, clutches, tyres, exhausts and brakes at competitive rates.","svcs":[("MOT Testing","Class 4 and 7 MOT testing with free retest within 10 days."),("Servicing & Repairs","Full and interim servicing plus general repairs for all makes."),("Clutches","Clutch replacements and dual mass flywheel repairs at competitive prices."),("Tyres","New and part-worn tyres. Wheel balancing and puncture repairs."),("Exhausts","Exhaust repairs and replacements with fast turnaround."),("Brakes","Brake pads, discs and fluid changes. Safety checked and guaranteed."),],"about":"K's Garage offers a wide range of motor repair services. From MOTs and servicing to major repairs, we help ensure you are always safe on the road at a competitive rate.","map":"https://www.google.com/maps?q=Newtown+SY164BQ&output=embed"},
    {"name":"Border Garage","slug":"border-garage","color":"#dc2626","phone":"01938 554 444","loc":"Welshpool, Powys, SY21 7BE","hours":"Monday - Friday: 8:00 - 17:30 | Saturday: 8:00 - 12:00","badge":"MOT Testing Station","hero":"Book your MOT online. Real-time 24/7 booking available","desc":"Local independent garage. Servicing, clutch, exhaust, diagnostics, brakes and online MOT booking.","svcs":[("MOT Testing","Book online 24/7 with real-time availability. Free retests within 10 days."),("Full & Interim Service","Comprehensive servicing using quality parts."),("Clutch Replacements","Fitting with original equipment quality parts and warranty."),("Exhaust Systems","Minor repairs to full replacements for all makes."),("Diagnostics","Full diagnostic scans and fault finding using the latest technology."),("Brake Services","Pads, discs, shoes and full hydraulic system servicing."),],"about":"Border Garage is your local independent garage with decades of experience and a commitment to customer service. We keep your vehicle safe and roadworthy.","map":"https://www.google.com/maps?q=Welshpool+SY217BE&output=embed"},
    {"name":"Evans Motors","slug":"evans-motors","color":"#166534","phone":"01597 810 289","loc":"Church Street, Rhayader, LD6 5BU","hours":"Monday - Friday: 8:30 - 17:00 | Saturday: 8:30 - 12:00","badge":"Established 1964","hero":"Family-run garage serving Rhayader since 1964","desc":"Comprehensive services for cars and light commercials. MOT, servicing, brakes, tyres, exhausts and more.","svcs":[("MOT Testing","Class 4 and 7 MOT. Walk-ins welcome but booking recommended."),("Servicing & Repairs","Comprehensive servicing and repairs for all makes and models."),("Brakes","Brake pads, discs and drum replacements. Safety guaranteed."),("Tyres","New, part-worn and winter tyres. Balancing, tracking and puncture repairs."),("Exhausts & Batteries","Exhaust repairs and battery replacements at competitive prices."),("Collection Available","Local collection and delivery service for your convenience."),],"about":"Evans Motors is a family-run business established in 1964. Our skilled mechanics provide a comprehensive range of services. We take pride in honest workmanship and customer care.","map":"https://www.google.com/maps?q=Rhayader+LD65BU&output=embed"},
    {"name":"J T Hughes Newtown","slug":"j-t-hughes-newtown","color":"#1e40af","phone":"01686 622 300","loc":"Newtown, Powys, SY16 3BD","hours":"Monday - Friday: 8:30 - 18:00 | Saturday: 9:00 - 17:00 | Sunday: Closed","badge":"Newtown's Local Garage","hero":"Your trusted local garage for MOTs, servicing and repairs","desc":"MOT testing, servicing, repairs, diagnostics, tyres and batteries. 6 days a week.","svcs":[("MOT Testing","Class 4 MOT testing available. Book online or by phone."),("Servicing","Interim and full services for all makes and models."),("Repairs","Mechanical repairs and maintenance to keep you roadworthy."),("Diagnostics","Fault finding and engine management diagnostics using modern equipment."),("Tyres & Batteries","Tyre fitting, balancing and battery testing and replacement."),("Brake Services","Full brake inspections, pad and disc replacements."),],"about":"J T Hughes is a trusted local garage in Newtown with convenient opening hours six days a week. Quality and reliability in everything we do.","map":"https://www.google.com/maps?q=Newtown+SY163BD&output=embed"},
]

T = '''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${name} — ${hero}</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<style>:root{--b:${color};--d:${dark}}
*{box-sizing:border-box}body{margin:0;padding:0;font-family:'Inter',sans-serif;color:#1a1a1a;background:#fff;line-height:1.6}
img{max-width:100%;display:block}
a{text-decoration:none;transition:all .2s}
.top-bar{background:var(--d);color:#fff;padding:10px 24px;font-size:.8rem;text-align:center}
.top-bar a{color:var(--b);font-weight:600}
nav{position:sticky;top:0;z-index:50;background:rgba(255,255,255,.97);backdrop-filter:blur(8px);border-bottom:1px solid #e5e5e5}
.nav-inner{max-width:1200px;margin:0 auto;padding:0 24px;display:flex;align-items:center;justify-content:space-between;height:68px}
.logo{font-weight:800;font-size:1.25rem;color:var(--b)}
.nav-links{display:flex;gap:36px;align-items:center}.nav-links a{font-weight:500;font-size:.9rem;color:#333}.nav-links a:hover{color:var(--b)}
.btn{background:var(--b);color:#fff;padding:10px 22px;border-radius:6px;font-weight:600;font-size:.85rem;display:inline-block;border:none;cursor:pointer}
.btn:hover{opacity:.9}
.btn-o{background:transparent;color:var(--b);padding:10px 18px;border-radius:6px;font-weight:600;font-size:.85rem;border:1.5px solid var(--b);display:inline-block;cursor:pointer}
.btn-o:hover{background:var(--b);color:#fff}
.hero{position:relative;height:600px;overflow:hidden}
.hero img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center}
.hero-overlay{position:absolute;inset:0;background:linear-gradient(90deg,${overlay} 0%,${overlay2} 60%,transparent 100%)}
.hero-content{position:absolute;inset:0;display:flex;align-items:center}
.hero-inner{max-width:1200px;margin:0 auto;padding:0 24px;width:100%}
.hero-text{max-width:560px}
.badge{display:inline-flex;align-items:center;gap:8px;background:${bg};border:1px solid rgba(255,255,255,.4);padding:6px 14px;border-radius:50px;font-size:.75rem;font-weight:600;color:#fff;text-transform:uppercase;letter-spacing:.08em;margin-bottom:20px}
.badge-dot{width:6px;height:6px;background:#fff;border-radius:50%;display:inline-block}
.hero h1{font-size:3.2rem;font-weight:800;color:#fff;line-height:1.05;letter-spacing:-.03em;margin:0 0 16px}
.hero p{font-size:1.15rem;color:rgba(255,255,255,.85);margin:0 0 28px;max-width:440px}
.hero-btns{display:flex;gap:14px;flex-wrap:wrap}
.btn-gh{background:transparent;color:#fff;padding:14px 24px;border-radius:8px;font-weight:600;font-size:1rem;border:1.5px solid rgba(255,255,255,.35);display:inline-block}.btn-gh:hover{border-color:#fff}
.trust{background:#f8f8f8;border-bottom:1px solid #e5e5e5}
.trust-inner{max-width:1200px;margin:0 auto;padding:32px 24px;display:flex;justify-content:space-around;align-items:center;flex-wrap:wrap;gap:24px}.trust-item{text-align:center}.trust-item strong{display:block;font-size:1.8rem;font-weight:800;color:var(--b)}.trust-item span{font-size:.8rem;color:#666;text-transform:uppercase;letter-spacing:.05em}
section{padding:80px 24px}.section-inner{max-width:1200px;margin:0 auto}
.section-header{text-align:center;margin-bottom:56px}.section-header span{display:inline-block;color:var(--b);font-weight:700;font-size:.7rem;text-transform:uppercase;letter-spacing:.18em;margin-bottom:12px}.section-header h2{font-size:2.4rem;font-weight:800;color:#1a1a1a;letter-spacing:-.02em;margin:0}.section-header p{color:#666;font-size:1.1rem;margin:12px auto 0;max-width:500px}
.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:32px}
.card{border:1px solid #e5e5e5;border-radius:12px;overflow:hidden;transition:all .3s}.card:hover{box-shadow:0 8px 24px rgba(0,0,0,.08)}.card img{width:100%;height:200px;object-fit:cover;object-position:center}.card-body{padding:28px}.card-body h3{font-size:1.2rem;font-weight:700;color:#1a1a1a;margin:0 0 8px}.card-body p{color:#666;font-size:.95rem;margin:0}
.about{background:#f8f8f8}.about-grid{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:center}.about-text span{display:inline-block;color:var(--b);font-weight:700;font-size:.7rem;text-transform:uppercase;letter-spacing:.18em;margin-bottom:12px}.about-text h2{font-size:2.4rem;font-weight:800;color:#1a1a1a;letter-spacing:-.02em;margin:0 0 20px}.about-text p{color:#444;font-size:1.05rem;margin:0 0 16px}.about-img{width:100%;border-radius:12px;box-shadow:0 20px 40px rgba(0,0,0,.12)}
.cta{background:var(--d);color:#fff;text-align:center}.cta-inner{max-width:800px;margin:0 auto}.cta span{display:inline-block;color:var(--b);font-weight:700;font-size:.7rem;text-transform:uppercase;letter-spacing:.18em;margin-bottom:16px}.cta h2{font-size:2.4rem;font-weight:800;margin:0 0 16px}.cta>p{font-size:1.1rem;color:rgba(255,255,255,.75);margin:0 0 28px}
.phone{font-size:2rem;font-weight:800;color:#fff;display:block;margin-bottom:8px;text-decoration:none}
.phone:hover{color:var(--b)}.hours{font-size:.85rem;color:rgba(255,255,255,.5);margin:0 0 20px}
footer{background:#0d0d0d;color:rgba(255,255,255,.4);padding:40px 24px 24px;font-size:.85rem}.footer-inner{max-width:1200px;margin:0 auto;display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:16px}footer strong{color:#fff;font-size:1rem}
.contact-sec{background:#f8f8f8;padding:80px 24px}.contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:40px;align-items:start}.contact-form{background:#fff;padding:40px;border-radius:12px;box-shadow:0 4px 20px rgba(0,0,0,.06)}.form-group{margin-bottom:20px}.form-group label{display:block;font-weight:600;font-size:.9rem;margin-bottom:8px;color:#1a1a1a}.form-group input,.form-group textarea{width:100%;padding:12px 16px;border:1px solid #e5e5e5;border-radius:8px;font-family:inherit;font-size:1rem}.form-group textarea{resize:vertical;min-height:120px}
.contact-details{background:#fff;padding:40px;border-radius:12px;box-shadow:0 4px 20px rgba(0,0,0,.06)}.contact-details h3{margin:0 0 16px;font-size:1.2rem}.contact-details p{margin:0 0 12px;color:#555;font-size:.95rem}.contact-details strong{color:#1a1a1a}
.map-frame{width:100%;height:280px;border-radius:8px;border:none;margin-top:16px}
.buy-bar{position:fixed;bottom:0;left:0;right:0;background:#fff;border-top:2px solid var(--b);padding:14px 24px;z-index:100;display:flex;justify-content:center;align-items:center;gap:20px;box-shadow:0 -4px 20px rgba(0,0,0,.1);flex-wrap:wrap}.buy-bar span{font-weight:600;color:#1a1a1a;font-size:.95rem}
.tier-panel{display:none;position:fixed;bottom:0;left:0;right:0;background:#f8f8f8;border-top:3px solid var(--b);padding:40px 24px 100px;z-index:90;max-height:90vh;overflow-y:auto;box-shadow:0 -8px 40px rgba(0,0,0,.15)}.tier-panel.active{display:block}.tiers{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}
.tier{background:#fff;border:2px solid #e5e5e5;border-radius:12px;padding:28px;text-align:center;position:relative;display:flex;flex-direction:column}.tier.featured{border-color:var(--b);box-shadow:0 8px 24px rgba(0,0,0,.08)}.tier-badge{position:absolute;top:-12px;left:50%;transform:translateX(-50%);background:var(--b);color:#fff;padding:4px 16px;border-radius:50px;font-size:.7rem;font-weight:700;text-transform:uppercase;letter-spacing:.1em}.tier h4{font-size:1.05rem;font-weight:700;color:#1a1a1a;margin:0 0 4px}.tier .price{font-size:2.2rem;font-weight:800;color:#1a1a1a;margin:0}.tier .price span{font-size:.85rem;font-weight:500;color:#888}.tier ul{list-style:none;padding:0;margin:0 0 20px;text-align:left;flex-grow:1}.tier ul li{padding:5px 0;border-bottom:1px solid #f0f0f0;color:#444;font-size:.85rem}.tier .btn{display:block;width:100%;padding:10px;border-radius:6px;font-weight:600;text-align:center;margin-bottom:8px}
.confirm-overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:200;align-items:center;justify-content:center}.confirm-overlay.active{display:flex}.confirm-box{background:#fff;border-radius:12px;padding:32px;max-width:420px;width:90%;text-align:center}
.removed-bar{display:none;position:fixed;bottom:0;left:0;right:0;background:#1a1a1a;color:#fff;padding:14px 24px;z-index:100;text-align:center}.removed-bar.active{display:block}.removed-bar a{color:var(--b);font-weight:600}
.success-msg{display:none;background:#ecfdf5;border:1px solid #a7f3d0;border-radius:12px;padding:40px;text-align:center;box-shadow:0 4px 20px rgba(0,0,0,.06)}.success-icon{width:48px;height:48px;background:#059669;color:#fff;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:1.5rem;margin:0 auto 16px}
@media(max-width:768px){.hero h1{font-size:2rem}.hero{height:400px}.cards,.tiers,.contact-grid{grid-template-columns:1fr}.about-grid{grid-template-columns:1fr}.nav-links{display:none}}
</style></head>
<body>

<div class="top-bar"><span>${loc}</span> | <a href="tel:${phone}">${phone}</a></div>

<nav><div class="nav-inner"><a href="#" class="logo">${name}</a><div class="nav-links"><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a><a href="tel:${phone}" class="btn">Call Now</a></div></div></nav>

<section class="hero">
<img src="${hero_img}" alt="${name}"><div class="hero-overlay"></div>
<div class="hero-content"><div class="hero-inner"><div class="hero-text">
<div class="badge"><span class="badge-dot"></span>${badge}</div>
<h1>${hero}</h1><p>${desc}</p>
<div class="hero-btns"><a href="tel:${phone}" class="btn" style="padding:14px 28px;font-size:1rem">Call ${phone}</a><a href="#services" class="btn-gh">Our Services</a></div>
</div></div></div>
</section>

<div class="trust"><div class="trust-inner"><div class="trust-item"><strong>${t1}</strong><span>${t1s}</span></div><div class="trust-item"><strong>${t2}</strong><span>${t2s}</span></div><div class="trust-item"><strong>${t3}</strong><span>${t3s}</span></div><div class="trust-item"><strong>${t4}</strong><span>${t4s}</span></div></div></div>

<section id="services"><div class="section-inner"><div class="section-header"><span>What We Offer</span><h2>Our Services</h2><p>Comprehensive garage services for cars and light commercial vehicles.</p></div><div class="cards">${cards}</div></div></section>

<section id="about" class="about"><div class="section-inner"><div class="about-grid"><div class="about-text"><span>About Us</span><h2>${about_h}</h2>${about_p}<a href="tel:${phone}" class="btn" style="margin-top:8px">Call Us Today</a></div><div><img src="${about_img}" alt="${name} workshop" class="about-img"></div></div></div></section>

<section id="contact" class="contact-sec"><div class="section-inner"><div class="section-header"><span>Get In Touch</span><h2>Contact ${name}</h2><p>Book your vehicle in, request a quote, or ask about our services.</p></div><div class="contact-grid"><div class="contact-form"><form id="cf"><div class="form-group"><label>Name</label><input type="text" name="name" required placeholder="Your name"></div><div class="form-group"><label>Email</label><input type="email" name="email" required placeholder="you@example.com"></div><div class="form-group"><label>Message</label><textarea name="message" rows="5" required placeholder="How can we help?"></textarea></div><button type="submit" class="btn" style="width:100%;border:none;cursor:pointer;padding:14px 24px;font-size:1rem">Send Message</button></form><div id="sf" class="success-msg"><div class="success-icon">&#10003;</div><h3 style="color:#065f46;margin:0 0 8px;font-size:1.2rem">Message Sent!</h3><p style="color:#047857;margin:0;font-size:.95rem">Thank you. We will get back to you within 24 hours.</p></div></div><div class="contact-details"><h3>${name}</h3><p><strong>Phone:</strong> <a href="tel:${phone}" style="color:var(--b);font-weight:600">${phone}</a></p><p><strong>Address:</strong> ${loc}</p><p><strong>Hours:</strong> ${hours}</p><iframe class="map-frame" src="${map}" loading="lazy" allowfullscreen></iframe></div></div></div></section>

<footer><div class="footer-inner"><div><strong>${name}</strong><span style="margin-left:16px">${loc}</span></div><div style="display:flex;gap:20px"><span>2024 ${name}</span></div></div></footer>

<div class="buy-bar" id="bb"><span>Want this site for your garage?</span><button class="btn" onclick="showTiers()">Get This Site - from 149</button><button class="btn-o" onclick="showNI()">Not For Me</button></div>

<div class="tier-panel" id="tp"><div class="section-inner" style="position:relative"><button style="position:absolute;top:0;right:0;font-size:1.5rem;color:#999;cursor:pointer;background:none;border:none" onclick="hideTiers()">&times;</button><h3 style="text-align:center;font-size:1.5rem;margin:0 0 8px">Get Your Site</h3><p style="text-align:center;color:#666;margin:0 0 32px">Pick the package that fits. No monthly fees. No lock-in.</p><div class="tiers"><div class="tier"><h4>Buy Outright</h4><p class="price">149 <span>one-time</span></p><ul><li>Complete page deployed live</li><li>Free Vercel account setup</li><li>Ownership transferred to you</li><li>Add your own custom domain</li></ul><a href="https://buy.stripe.com/14AaENc4oeYBgfk26R5EY0f" class="btn btn-primary">Buy - 149</a></div><div class="tier featured"><div class="tier-badge">Popular</div><h4>Hosted + Edits</h4><p class="price">399 <span>one-time</span></p><ul><li>Live deployment to Vercel</li><li>12 months hosting included</li><li>2 rounds of edits included</li><li>Email support</li></ul><a href="https://buy.stripe.com/fZu4gpecw2bPbZ4dPz5EY0g" class="btn btn-primary">Buy - 399</a></div><div class="tier"><h4>Premium</h4><p class="price">997 <span>first 12 months</span></p><ul><li>Everything in Hosted + Edits</li><li>Voice AI chatbot bolt-on</li><li>Unlimited edits for 12 months</li><li>Priority support</li></ul><button class="btn" onclick="alert('Contact tyrone@propagate.media for Premium setup')">Get This</button></div></div></div></div>

<div class="confirm-overlay" id="co"><div class="confirm-box"><h3>Remove This Demo?</h3><p>This will permanently delete the demo page for ${name}.</p><div style="display:flex;gap:12px;justify-content:center"><button class="btn-o" onclick="hideNI()">Keep It</button><button class="btn" onclick="doDel()" style="background:#666;border-color:#666">Delete Demo</button></div></div></div>
<div class="removed-bar" id="rb"><p>This demo has been permanently removed. <a href="mailto:freshsites@sites.propagate.media">Email us</a> if you change your mind.</p></div>

<script>function showTiers(){document.getElementById('tp').classList.add('active');document.getElementById('bb').style.display='none'}function hideTiers(){document.getElementById('tp').classList.remove('active');document.getElementById('bb').style.display='flex'}function showNI(){document.getElementById('co').classList.add('active')}function hideNI(){document.getElementById('co').classList.remove('active')}function doDel(){document.getElementById('co').classList.remove('active');document.getElementById('bb').style.display='none';document.getElementById('tp').classList.remove('active');document.getElementById('rb').classList.add('active')}document.getElementById('cf').addEventListener('submit',function(e){e.preventDefault();document.getElementById('cf').style.display='none';document.getElementById('sf').style.display='block'});document.getElementById('co').addEventListener('click',function(e){if(e.target===this)hideNI()});document.getElementById('tp').addEventListener('click',function(e){if(e.target===this)hideTiers()})</script>

</body></html>'''

def build(lead):
    svc_imgs=[IMAGES["svc_workshop"],IMAGES["svc_diagnostics"],IMAGES["svc_tyres"],IMAGES["svc_brakes"],IMAGES["svc_servicing"],IMAGES["svc_engine"]]
    cards="".join(f'<div class="card"><img src="{svc_imgs[i%len(svc_imgs)]}" alt="{s[0]}" loading="lazy"><div class="card-body"><h3>{s[0]}</h3><p>{s[1]}</p></div></div>' for i,s in enumerate(lead["svcs"]))
    about_p="".join(f'<p>{p.strip()}{"" if p.strip().endswith(".") else "."}</p>' for p in lead["about"].split(". ") if p.strip())
    years=lead["badge"].replace("Established ","").replace("Family Run Since ","").replace("+","").replace(" Years Experience","")
    values={"name":lead["name"],"slug": lead["slug"],"color":lead["color"],"dark":"#1a1a1a","overlay":lead["color"]+"d9","overlay2":"#1a1a1acc","bg":lead["color"]+"4d",
        "phone":lead["phone"],"loc":lead["loc"],"hours":lead["hours"],"badge":lead["badge"],"hero":lead["hero"],"desc":lead["desc"],
        "hero_img":IMAGES["hero_workshop"],"about_img":IMAGES["about_mechanic"],"t1":years,"t1s":("Since "+years if years.isdigit() else "Experience"),"t2":"All Makes","t2s":"& Models","t3":"MOT","t3s":"Testing","t4":"Parts","t4s":"& Labour",
        "cards":cards,"about_h":"Your Trusted "+lead["loc"].split(",")[0]+" Garage","about_p":about_p,"map":lead["map"],
    }
    return Template(T).substitute(values)

demos=Path("demos")
demos.mkdir(exist_ok=True)
for lead in LEADS:
    path=demos/f"{lead['slug']}.html"
    path.write_text(build(lead),encoding="utf-8")
    print(f"Wrote: {path}")

# Copy to docs and push
docs=Path("docs/demos")
docs.mkdir(parents=True,exist_ok=True)
import shutil
for f in demos.glob("*.html"):
    shutil.copy(f,docs/f.name)
print("\nCopied to docs/demos/")
